add test showing failure to subclass when __init__ has a parameter
Error appears to be that the subclass is treated as though it has a
__new__ method of the base class, preventing changing the arguments to
the __init__ method. Actually it is worse, since the semantics is
different. The base new is called before the subclass __init__ (as it
should) but that means the initialization in the base is also called
before, meaning we cannot have something like.

class RustBase:
        def __init__(self, x):
                self.x = x

class Sub(RustBase):
        def __init__(self, y):
                super().__init__(y * 2)

tests/test_subclassing.py .F                                                                                                                                                                                  [100%]

===================================================================================================== FAILURES ====================================================================================================
______________________________________________________________________________________________ test_subclass_with_init ____________________________________________________________________________________________

    def test_subclass_with_init():
>       s = SubclassWithExtraInitArguments(10)
E       TypeError: argument 'foo': 'int' object cannot be converted to 'PyBool'

tests/test_subclassing.py:27: TypeError
============================================================================================== short test summary info ============================================================================================
FAILED tests/test_subclassing.py::test_subclass_with_init - TypeError: argument 'foo': 'int' object cannot be converted to 'PyBool'
=========================================================================================== 1 failed, 64 passed in 1.07s ==========================================================================================